version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: stock-manager-app
    ports:
      - "3000:3000"
    volumes:
      - ./prisma/data:/app/prisma/data
    environment:
      - DATABASE_URL=file:./data/prod.db
      - NODE_ENV=production
    restart: unless-stopped
